stages:
- stage: validate
  jobs:
  - job: validate
    continueOnError: false
    steps: 
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV3@3
      displayName: 'init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'Azure Pass - Sponsorship (85ba23e3-1754-41e4-952c-b2d1c4e400a3)'
        backendAzureRmResourceGroupName: 'rg-stage'
        backendAzureRmStorageAccountName: 'terraformstarageaccount'
        backendAzureRmContainerName: 'tfcontainer'
        backendAzureRmKey: 'terraform.tfstate'
    
    - task: TerraformTaskV3@3
      displayName: 'validate'
      inputs:
        provider: 'azurerm'
        command: 'validate'

- stage: deploy
  jobs:
  - deployment: deploy_terraform
    continueOnError: false 
    environment: 'stage'
    strategy:
     runOnce:
       deploy:
         steps:
           - checkout: self
           - task: TerraformInstaller@0
             displayName: 'install'
             inputs:
               terraformVersion: 'latest'

           - task: TerraformTaskV3@3
             displayName: 'init'
             inputs:
               provider: 'azurerm'
               command: 'init'
               backendServiceArm: 'Azure Pass - Sponsorship (85ba23e3-1754-41e4-952c-b2d1c4e400a3)'
               backendAzureRmResourceGroupName: 'rg-stage'
               backendAzureRmStorageAccountName: 'terraformstarageaccount'
               backendAzureRmContainerName: 'tfcontainer'
               backendAzureRmKey: 'terraform.tfstate'
               
           - task: TerraformTaskV3@3
             displayName: 'plan'
             inputs:
               provider: 'azurerm'
               command: 'plan'
               environmentServiceNameAzureRM: 'Azure Pass - Sponsorship (85ba23e3-1754-41e4-952c-b2d1c4e400a3)'
           - task: TerraformTaskV3@3
             displayName: 'plan'
             inputs:
               provider: 'azurerm'
               command: 'apply'
               environmentServiceNameAzureRM: 'Azure Pass - Sponsorship (85ba23e3-1754-41e4-952c-b2d1c4e400a3)'